%########################################################################
%# Copyright (c) 1988-2022 $organization$
%#
%# This software is provided by the author and contributors ``as is'' 
%# and any express or implied warranties, including, but not limited to, 
%# the implied warranties of merchantability and fitness for a particular 
%# purpose are disclaimed. In no event shall the author or contributors 
%# be liable for any direct, indirect, incidental, special, exemplary, 
%# or consequential damages (including, but not limited to, procurement 
%# of substitute goods or services; loss of use, data, or profits; or 
%# business interruption) however caused and on any theory of liability, 
%# whether in contract, strict liability, or tort (including negligence 
%# or otherwise) arising in any way out of the use of this software, 
%# even if advised of the possibility of such damage.
%#
%#   File: props-props.t
%#
%# Author: $author$
%#   Date: 10/9/2022
%########################################################################
%with(%
%is_include_path,%(%else-then(%is_include_path%,%(%is_Include_path%)%)%)%,%
%include_path,%(%else-then(%if-no(%is_include_path%,,%(%include_path%)%)%,%(%if-no(%is_include_path%,,%(%filepath(%input%)%)%)%)%)%)%,%
%Include_path,%(%else-then(%if-no(%is_include_path%,,%(%Include_path%)%)%,%(%if-no(%is_include_path%,,%(%include_path%)%)%)%)%)%,%
%INCLUDE_PATH,%(%else-then(%INCLUDE_PATH%,%(%toupper(%Include_path%)%)%)%)%,%
%include_path,%(%else-then(%_include_path%,%(%tolower(%Include_path%)%)%)%)%,%
%is_framework,%(%else-then(%is_framework%,%(%is_Framework%)%)%)%,%
%framework,%(%else-then(%if-no(%is_framework%,,%(%framework%)%)%,%(%if-no(%is_framework%,,%(%
%%else-then(%include(%Include_path%/../t/Framework.t)%,%(Framework)%)%%
%)%)%)%)%)%,%
%Framework,%(%else-then(%if-no(%is_framework%,,%(%Framework%)%)%,%(%if-no(%is_framework%,,%(%framework%)%)%)%)%)%,%
%FRAMEWORK,%(%else-then(%FRAMEWORK%,%(%toupper(%Framework%)%)%)%)%,%
%framework,%(%else-then(%_framework%,%(%tolower(%Framework%)%)%)%)%,%
%is_depends,%(%else-then(%is_depends%,%(%is_Depends%)%)%)%,%
%depends,%(%else-then(%if-no(%is_depends%,,%(%depends%)%)%,%(%if-no(%is_depends%,,%(%
%%else-then(%include(%Include_path%/../t/Framework-depends.t)%,%()%)%%
%)%)%)%)%)%,%
%Depends,%(%else-then(%if-no(%is_depends%,,%(%Depends%)%)%,%(%if-no(%is_depends%,,%(%depends%)%)%)%)%)%,%
%DEPENDS,%(%else-then(%DEPENDS%,%(%toupper(%Depends%)%)%)%)%,%
%depends,%(%else-then(%_depends%,%(%tolower(%Depends%)%)%)%)%,%
%is_depend,%(%else-then(%is_depend%,%(%is_Depend%)%)%)%,%
%depend,%(%else-then(%if-no(%is_depend%,,%(%depend%)%)%,%(%if-no(%is_depend%,,%(%Depends%)%)%)%)%)%,%
%Depend,%(%else-then(%if-no(%is_depend%,,%(%Depend%)%)%,%(%if-no(%is_depend%,,%(%depend%)%)%)%)%)%,%
%DEPEND,%(%else-then(%DEPEND%,%(%toupper(%Depend%)%)%)%)%,%
%depend,%(%else-then(%_depend%,%(%tolower(%Depend%)%)%)%)%,%
%is_base,%(%else-then(%is_base%,%(%is_Base%)%)%)%,%
%base,%(%else-then(%if-no(%is_base%,,%(%base%)%)%,%(%if-no(%is_base%,,%(%else-then(%filebase(%File%)%,%Framework%)%)%)%)%)%)%,%
%Base,%(%else-then(%if-no(%is_base%,,%(%Base%)%)%,%(%if-no(%is_base%,,%(%base%)%)%)%)%)%,%
%BASE,%(%else-then(%BASE%,%(%toupper(%Base%)%)%)%)%,%
%base,%(%else-then(%_base%,%(%tolower(%Base%)%)%)%)%,%
%is_name,%(%else-then(%is_name%,%(%is_Name%)%)%)%,%
%name,%(%else-then(%if-no(%is_name%,,%(%name%)%)%,%(%if-no(%is_name%,,%(%Base%)%)%)%)%)%,%
%Name,%(%else-then(%if-no(%is_name%,,%(%Name%)%)%,%(%if-no(%is_name%,,%(%name%)%)%)%)%)%,%
%NAME,%(%else-then(%NAME%,%(%toupper(%Name%)%)%)%)%,%
%name,%(%else-then(%_name%,%(%tolower(%Name%)%)%)%)%,%
%is_inheritedpropertysheets,%(%else-then(%is_inheritedpropertysheets%,%(%is_InheritedPropertySheets%)%)%)%,%
%inheritedpropertysheets,%(%else-then(%if-no(%is_inheritedpropertysheets%,,%(%inheritedpropertysheets%)%)%,%(%if-no(%is_inheritedpropertysheets%,,%(%
%%include(%Include_path%/InheritedPropertySheets-props.t)%%
%)%)%)%)%)%,%
%InheritedPropertySheets,%(%else-then(%if-no(%is_inheritedpropertysheets%,,%(%InheritedPropertySheets%)%)%,%(%if-no(%is_inheritedpropertysheets%,,%(%inheritedpropertysheets%)%)%)%)%)%,%
%INHERITEDPROPERTYSHEETS,%(%else-then(%INHERITEDPROPERTYSHEETS%,%(%toupper(%InheritedPropertySheets%)%)%)%)%,%
%inheritedpropertysheets,%(%else-then(%_inheritedpropertysheets%,%(%tolower(%InheritedPropertySheets%)%)%)%)%,%
%is_user_macro,%(%else-then(%is_user_macro%,%(%is_USER_MACRO%)%)%)%,%
%is_name_group,%(%else-then(%is_name_group%,%(%is_NAME_GROUP%)%)%)%,%
%name_group,%(%else-then(%if-no(%is_name_group%,,%(%name_group%)%)%,%(%if-no(%is_name_group%,,%(%
%%Group%%
%)%)%)%)%)%,%
%NAME_GROUP,%(%else-then(%if-no(%is_name_group%,,%(%NAME_GROUP%)%)%,%(%if-no(%is_name_group%,,%(%name_group%)%)%)%)%)%,%
%NAME_GROUP,%(%else-then(%NAME_GROUP%,%(%toupper(%NAME_GROUP%)%)%)%)%,%
%name_group,%(%else-then(%_name_group%,%(%tolower(%NAME_GROUP%)%)%)%)%,%
%is_name_name,%(%else-then(%is_name_name%,%(%is_NAME_NAME%)%)%)%,%
%name_name,%(%else-then(%if-no(%is_name_name%,,%(%name_name%)%)%,%(%if-no(%is_name_name%,,%(%
%%Name%%
%)%)%)%)%)%,%
%NAME_NAME,%(%else-then(%if-no(%is_name_name%,,%(%NAME_NAME%)%)%,%(%if-no(%is_name_name%,,%(%name_name%)%)%)%)%)%,%
%NAME_NAME,%(%else-then(%NAME_NAME%,%(%toupper(%NAME_NAME%)%)%)%)%,%
%name_name,%(%else-then(%_name_name%,%(%tolower(%NAME_NAME%)%)%)%)%,%
%is_name_version,%(%else-then(%is_name_version%,%(%is_NAME_VERSION%)%)%)%,%
%name_version,%(%else-then(%if-no(%is_name_version%,,%(%name_version%)%)%,%(%if-no(%is_name_version%,,%(%
%%Version%%
%)%)%)%)%)%,%
%NAME_VERSION,%(%else-then(%if-no(%is_name_version%,,%(%NAME_VERSION%)%)%,%(%if-no(%is_name_version%,,%(%name_version%)%)%)%)%)%,%
%NAME_VERSION,%(%else-then(%NAME_VERSION%,%(%toupper(%NAME_VERSION%)%)%)%)%,%
%name_version,%(%else-then(%_name_version%,%(%tolower(%NAME_VERSION%)%)%)%)%,%
%is_name_dir,%(%else-then(%is_name_dir%,%(%is_NAME_DIR%)%)%)%,%
%name_dir,%(%else-then(%if-no(%is_name_dir%,,%(%name_dir%)%)%,%(%if-no(%is_name_dir%,,%(%
%$%(()%%NAME%_GROUP%())%$%(()%%NAME%_NAME%())%$%(()%%NAME%_VERSION%())%%
%)%)%)%)%)%,%
%NAME_DIR,%(%else-then(%if-no(%is_name_dir%,,%(%NAME_DIR%)%)%,%(%if-no(%is_name_dir%,,%(%name_dir%)%)%)%)%)%,%
%NAME_DIR,%(%else-then(%NAME_DIR%,%(%toupper(%NAME_DIR%)%)%)%)%,%
%name_dir,%(%else-then(%_name_dir%,%(%tolower(%NAME_DIR%)%)%)%)%,%
%is_name_source_dir,%(%else-then(%is_name_source_dir%,%(%is_NAME_SOURCE_DIR%)%)%)%,%
%name_source_dir,%(%else-then(%if-no(%is_name_source_dir%,,%(%name_source_dir%)%)%,%(%if-no(%is_name_source_dir%,,%(%
%$%(()%SOURCE_ROOT_DIR%())%/$%(()%%NAME%_DIR%())%/%Source%%
%)%)%)%)%)%,%
%NAME_SOURCE_DIR,%(%else-then(%if-no(%is_name_source_dir%,,%(%NAME_SOURCE_DIR%)%)%,%(%if-no(%is_name_source_dir%,,%(%name_source_dir%)%)%)%)%)%,%
%NAME_SOURCE_DIR,%(%else-then(%NAME_SOURCE_DIR%,%(%toupper(%NAME_SOURCE_DIR%)%)%)%)%,%
%name_source_dir,%(%else-then(%_name_source_dir%,%(%tolower(%NAME_SOURCE_DIR%)%)%)%)%,%
%is_name_build_dir,%(%else-then(%is_name_build_dir%,%(%is_NAME_BUILD_DIR%)%)%)%,%
%name_build_dir,%(%else-then(%if-no(%is_name_build_dir%,,%(%name_build_dir%)%)%,%(%if-no(%is_name_build_dir%,,%(%
%$%(()%SOURCE_BUILD_DIR%())%/$%(()%%NAME%_DIR%())%/%Build%%
%)%)%)%)%)%,%
%NAME_BUILD_DIR,%(%else-then(%if-no(%is_name_build_dir%,,%(%NAME_BUILD_DIR%)%)%,%(%if-no(%is_name_build_dir%,,%(%name_build_dir%)%)%)%)%)%,%
%NAME_BUILD_DIR,%(%else-then(%NAME_BUILD_DIR%,%(%toupper(%NAME_BUILD_DIR%)%)%)%)%,%
%name_build_dir,%(%else-then(%_name_build_dir%,%(%tolower(%NAME_BUILD_DIR%)%)%)%)%,%
%is_name_build,%(%else-then(%is_name_build%,%(%is_NAME_BUILD%)%)%)%,%
%name_build,%(%else-then(%if-no(%is_name_build%,,%(%name_build%)%)%,%(%if-no(%is_name_build%,,%(%
%$%(()%%NAME%_BUILD_DIR%())%/$%(()%PlatformName%())%/$%(()%VCVersion%())%/$%(()%ConfigurationName%())%%
%)%)%)%)%)%,%
%NAME_BUILD,%(%else-then(%if-no(%is_name_build%,,%(%NAME_BUILD%)%)%,%(%if-no(%is_name_build%,,%(%name_build%)%)%)%)%)%,%
%NAME_BUILD,%(%else-then(%NAME_BUILD%,%(%toupper(%NAME_BUILD%)%)%)%)%,%
%name_build,%(%else-then(%_name_build%,%(%tolower(%NAME_BUILD%)%)%)%)%,%
%is_name_obj,%(%else-then(%is_name_obj%,%(%is_NAME_OBJ%)%)%)%,%
%name_obj,%(%else-then(%if-no(%is_name_obj%,,%(%name_obj%)%)%,%(%if-no(%is_name_obj%,,%(%
%$%(()%%NAME%_BUILD%())%/obj/$%(()%ProjectName%())%%
%)%)%)%)%)%,%
%NAME_OBJ,%(%else-then(%if-no(%is_name_obj%,,%(%NAME_OBJ%)%)%,%(%if-no(%is_name_obj%,,%(%name_obj%)%)%)%)%)%,%
%NAME_OBJ,%(%else-then(%NAME_OBJ%,%(%toupper(%NAME_OBJ%)%)%)%)%,%
%name_obj,%(%else-then(%_name_obj%,%(%tolower(%NAME_OBJ%)%)%)%)%,%
%is_name_lib,%(%else-then(%is_name_lib%,%(%is_NAME_LIB%)%)%)%,%
%name_lib,%(%else-then(%if-no(%is_name_lib%,,%(%name_lib%)%)%,%(%if-no(%is_name_lib%,,%(%
%$%(()%%NAME%_BUILD%())%/lib%
%)%)%)%)%)%,%
%NAME_LIB,%(%else-then(%if-no(%is_name_lib%,,%(%NAME_LIB%)%)%,%(%if-no(%is_name_lib%,,%(%name_lib%)%)%)%)%)%,%
%NAME_LIB,%(%else-then(%NAME_LIB%,%(%toupper(%NAME_LIB%)%)%)%)%,%
%name_lib,%(%else-then(%_name_lib%,%(%tolower(%NAME_LIB%)%)%)%)%,%
%is_name_bin,%(%else-then(%is_name_bin%,%(%is_NAME_BIN%)%)%)%,%
%name_bin,%(%else-then(%if-no(%is_name_bin%,,%(%name_bin%)%)%,%(%if-no(%is_name_bin%,,%(%
%$%(()%%NAME%_BUILD%())%/bin%
%)%)%)%)%)%,%
%NAME_BIN,%(%else-then(%if-no(%is_name_bin%,,%(%NAME_BIN%)%)%,%(%if-no(%is_name_bin%,,%(%name_bin%)%)%)%)%)%,%
%NAME_BIN,%(%else-then(%NAME_BIN%,%(%toupper(%NAME_BIN%)%)%)%)%,%
%name_bin,%(%else-then(%_name_bin%,%(%tolower(%NAME_BIN%)%)%)%)%,%
%is_name_defines,%(%else-then(%is_name_defines%,%(%is_NAME_DEFINES%)%)%)%,%
%name_defines,%(%else-then(%if-no(%is_name_defines%,,%(%name_defines%)%)%,%(%if-no(%is_name_defines%,,%(%
%XOS_LIB_%NAME%_VERSION_BUILD_DATE=%date()%%
%)%)%)%)%)%,%
%NAME_DEFINES,%(%else-then(%if-no(%is_name_defines%,,%(%NAME_DEFINES%)%)%,%(%if-no(%is_name_defines%,,%(%name_defines%)%)%)%)%)%,%
%NAME_DEFINES,%(%else-then(%NAME_DEFINES%,%(%toupper(%NAME_DEFINES%)%)%)%)%,%
%name_defines,%(%else-then(%_name_defines%,%(%tolower(%NAME_DEFINES%)%)%)%)%,%
%is_name_debug_defines,%(%else-then(%is_name_debug_defines%,%(%is_NAME_DEBUG_DEFINES%)%)%)%,%
%name_debug_defines,%(%else-then(%if-no(%is_name_debug_defines%,,%(%name_debug_defines%)%)%,%(%if-no(%is_name_debug_defines%,,%(%
%%if-then(%parse(%DEPEND%,;,,,,%($%(()%%DEPEND%_DEBUG_DEFINES%())%;)%,DEPEND)%,%($%(()%WINDOWS_DEBUG_DEFINES%())%;)%)%$%(()%%NAME%_DEFINES%())%%
%)%)%)%)%)%,%
%NAME_DEBUG_DEFINES,%(%else-then(%if-no(%is_name_debug_defines%,,%(%NAME_DEBUG_DEFINES%)%)%,%(%if-no(%is_name_debug_defines%,,%(%name_debug_defines%)%)%)%)%)%,%
%NAME_DEBUG_DEFINES,%(%else-then(%NAME_DEBUG_DEFINES%,%(%toupper(%NAME_DEBUG_DEFINES%)%)%)%)%,%
%name_debug_defines,%(%else-then(%_name_debug_defines%,%(%tolower(%NAME_DEBUG_DEFINES%)%)%)%)%,%
%is_name_release_defines,%(%else-then(%is_name_release_defines%,%(%is_NAME_RELEASE_DEFINES%)%)%)%,%
%name_release_defines,%(%else-then(%if-no(%is_name_release_defines%,,%(%name_release_defines%)%)%,%(%if-no(%is_name_release_defines%,,%(%
%%if-then(%parse(%DEPEND%,;,,,,%($%(()%%DEPEND%_RELEASE_DEFINES%())%;)%,DEPEND)%,%($%(()%WINDOWS_RELEASE_DEFINES%())%;)%)%$%(()%%NAME%_DEFINES%())%%
%)%)%)%)%)%,%
%NAME_RELEASE_DEFINES,%(%else-then(%if-no(%is_name_release_defines%,,%(%NAME_RELEASE_DEFINES%)%)%,%(%if-no(%is_name_release_defines%,,%(%name_release_defines%)%)%)%)%)%,%
%NAME_RELEASE_DEFINES,%(%else-then(%NAME_RELEASE_DEFINES%,%(%toupper(%NAME_RELEASE_DEFINES%)%)%)%)%,%
%name_release_defines,%(%else-then(%_name_release_defines%,%(%tolower(%NAME_RELEASE_DEFINES%)%)%)%)%,%
%is_name_include_dirs,%(%else-then(%is_name_include_dirs%,%(%is_NAME_INCLUDE_DIRS%)%)%)%,%
%name_include_dirs,%(%else-then(%if-no(%is_name_include_dirs%,,%(%name_include_dirs%)%)%,%(%if-no(%is_name_include_dirs%,,%(%
%$%(()%%NAME%_SOURCE_DIR%())%%if-then(%reverse-parse(%DEPEND%,;,,,,%(;$%(()%%DEPEND%_SOURCE_DIR%())%)%,DEPEND)%,%(;$%(()%WINDOWS_INCLUDE_DIRS%())%)%)%%
%)%)%)%)%)%,%
%NAME_INCLUDE_DIRS,%(%else-then(%if-no(%is_name_include_dirs%,,%(%NAME_INCLUDE_DIRS%)%)%,%(%if-no(%is_name_include_dirs%,,%(%name_include_dirs%)%)%)%)%)%,%
%NAME_INCLUDE_DIRS,%(%else-then(%NAME_INCLUDE_DIRS%,%(%toupper(%NAME_INCLUDE_DIRS%)%)%)%)%,%
%name_include_dirs,%(%else-then(%_name_include_dirs%,%(%tolower(%NAME_INCLUDE_DIRS%)%)%)%)%,%
%is_name_lib_dirs,%(%else-then(%is_name_lib_dirs%,%(%is_NAME_LIB_DIRS%)%)%)%,%
%name_lib_dirs,%(%else-then(%if-no(%is_name_lib_dirs%,,%(%name_lib_dirs%)%)%,%(%if-no(%is_name_lib_dirs%,,%(%
%$%(()%%NAME%_LIB%())%%if-then(%reverse-parse(%DEPEND%,;,,,,%(;$%(()%%DEPEND%_LIB%())%)%,DEPEND)%,,%(;$%(()%WINDOWS_LIB_DIRS%())%)%)%%
%)%)%)%)%)%,%
%NAME_LIB_DIRS,%(%else-then(%if-no(%is_name_lib_dirs%,,%(%NAME_LIB_DIRS%)%)%,%(%if-no(%is_name_lib_dirs%,,%(%name_lib_dirs%)%)%)%)%)%,%
%NAME_LIB_DIRS,%(%else-then(%NAME_LIB_DIRS%,%(%toupper(%NAME_LIB_DIRS%)%)%)%)%,%
%name_lib_dirs,%(%else-then(%_name_lib_dirs%,%(%tolower(%NAME_LIB_DIRS%)%)%)%)%,%
%is_name_libs,%(%else-then(%is_name_libs%,%(%is_NAME_LIBS%)%)%)%,%
%name_libs,%(%else-then(%if-no(%is_name_libs%,,%(%name_libs%)%)%,%(%if-no(%is_name_libs%,,%(%
%lib%Name%.lib%if-then(%reverse-parse(%Depend%,;,,,,%( lib%Depend%.lib)%,Depend)%,%( $%(()%WINDOWS_LIBS%())%)%)%%
%)%)%)%)%)%,%
%NAME_LIBS,%(%else-then(%if-no(%is_name_libs%,,%(%NAME_LIBS%)%)%,%(%if-no(%is_name_libs%,,%(%name_libs%)%)%)%)%)%,%
%NAME_LIBS,%(%else-then(%NAME_LIBS%,%(%toupper(%NAME_LIBS%)%)%)%)%,%
%name_libs,%(%else-then(%_name_libs%,%(%tolower(%NAME_LIBS%)%)%)%)%,%
%is_buildmacros,%(%else-then(%is_buildmacros%,%(%is_BuildMacros%)%)%)%,%
%buildmacros,%(%else-then(%if-no(%is_buildmacros%,,%(%buildmacros%)%)%,%(%if-no(%is_buildmacros%,,%(%
%%if-then(%parse(%UserMacro%,;,,%(,)%,,%(%
%%with(%
%is_macro_name,%(%else-then(%is_macro_name%,%(%is_Macro_name%)%)%)%,%
%macro_name,%(%else-then(%if-no(%is_macro_name%,,%(%macro_name%)%)%,%(%if-no(%is_macro_name%,,%(%else-then(%left(%UserMacro%)%,%UserMacro%)%)%)%)%)%)%,%
%Macro_name,%(%else-then(%if-no(%is_macro_name%,,%(%Macro_name%)%)%,%(%if-no(%is_macro_name%,,%(%macro_name%)%)%)%)%)%,%
%MACRO_NAME,%(%else-then(%MACRO_NAME%,%(%toupper(%Macro_name%)%)%)%)%,%
%macro_name,%(%else-then(%_macro_name%,%(%tolower(%Macro_name%)%)%)%)%,%
%is_macro_value,%(%else-then(%is_macro_value%,%(%is_Macro_value%)%)%)%,%
%macro_value,%(%else-then(%if-no(%is_macro_value%,,%(%macro_value%)%)%,%(%if-no(%is_macro_value%,,%(%else-then(%right-of-left(%UserMacro%)%,)%)%)%)%)%)%,%
%Macro_value,%(%else-then(%if-no(%is_macro_value%,,%(%Macro_value%)%)%,%(%if-no(%is_macro_value%,,%(%macro_value%)%)%)%)%)%,%
%MACRO_VALUE,%(%else-then(%MACRO_VALUE%,%(%toupper(%Macro_value%)%)%)%)%,%
%macro_value,%(%else-then(%_macro_value%,%(%tolower(%Macro_value%)%)%)%)%,%
%%(%Macro_name%=%Macro_value%)%)%%
%)%,UserMacro)%,%(,)%)%%
%%NAME%_GROUP=%NAME_GROUP%%
%,%NAME%_NAME=%NAME_NAME%%
%,%NAME%_VERSION=%NAME_VERSION%%
%,%NAME%_DIR=%NAME_DIR%%
%,%NAME%_SOURCE_DIR=%NAME_SOURCE_DIR%%
%,%NAME%_BUILD_DIR=%NAME_BUILD_DIR%%
%,%NAME%_BUILD=%NAME_BUILD%%
%,%NAME%_OBJ=%NAME_OBJ%%
%,%NAME%_LIB=%NAME_LIB%%
%,%NAME%_BIN=%NAME_BIN%%
%,%NAME%_DEFINES=%NAME_DEFINES%%
%,%NAME%_DEBUG_DEFINES=%NAME_DEBUG_DEFINES%%
%,%NAME%_RELEASE_DEFINES=%NAME_RELEASE_DEFINES%%
%,%NAME%_INCLUDE_DIRS=%NAME_INCLUDE_DIRS%%
%,%NAME%_LIB_DIRS=%NAME_LIB_DIRS%%
%,%NAME%_LIBS=%NAME_LIBS%%
%)%)%)%)%)%,%
%BuildMacros,%(%else-then(%if-no(%is_buildmacros%,,%(%BuildMacros%)%)%,%(%if-no(%is_buildmacros%,,%(%buildmacros%)%)%)%)%)%,%
%BUILDMACROS,%(%else-then(%BUILDMACROS%,%(%toupper(%BuildMacros%)%)%)%)%,%
%buildmacros,%(%else-then(%_buildmacros%,%(%tolower(%BuildMacros%)%)%)%)%,%
%%(%
%%include(%Include_path%/props.t)%%
%<!--
=====================================================================
$(%NAME%_BIN)
$(%NAME%_LIB)
$(%NAME%_OBJ)
%if-then(%InheritedPropertySheets%,%(
)%)%$(%NAME%_INCLUDE_DIRS)
$(%NAME%_LIB_DIRS)
$(%NAME%_LIBS)
$(%NAME%_DEBUG_DEFINES)
$(%NAME%_RELEASE_DEFINES)
$(%NAME%_EXE_DEBUG_DEFINES)
$(%NAME%_EXE_RELEASE_DEFINES)
=====================================================================
-->
%
%)%)%